// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./navbar";
import PopupModal from "./components/popup-modal";
import Footer from "./footer";
import { CartProvider } from "./context/cartContext";
import { AuthProvider } from "./context/authContext"; 

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
            <AuthProvider> {/* Wrap with AuthProvider */}
              <Navbar />
              <PopupModal canScroll={true}/>
              <PopupModal spec={true}/>
              {children}
              <Footer />
            </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
